using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace GarageApplicationGroup4
{
    public class Graphics
    {
        public void Hellomessage()
        {
            int pN = Garage<Vehicle>.Get().vehicles.Count();
            int mN = Garage<Vehicle>.Get().MaxLimit;
            int fS = (mN - pN);



            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 _______________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("            _____________________                                                ||     |   |       |   |      ||");
            Console.WriteLine("     _    /|         |           \\                                               ||     |___|       |___|      ||");
            Console.WriteLine("    _|\\__/ |........ |............\\__________                                    ||      ___         ___       ||");
            Console.WriteLine("    |                   -*                    \\                                  ||     |   |       |   |      ||");
            Console.WriteLine("    |      ...                    ...          \\<<                               ||     |___|       |___|      ||");
            Console.WriteLine("    |_____( ¤ )__________________( ¤ )_________|                                 ||                            ||");
            Console.WriteLine("...........'''....................'''............................................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("               _____________________                                             ||     |   |       |   |      ||");
            Console.WriteLine("        _    /|         |           \\                                            ||     |___|       |___|      ||");
            Console.WriteLine("  Wel  _|\\__/ |........ |............\\__________                                 ||      ___         ___       ||");
            Console.WriteLine("       |                   -*                    \\                               ||     |   |       |   |      ||");
            Console.WriteLine("       |      ...                    ...          \\<<                            ||     |___|       |___|      ||");
            Console.WriteLine("       |_____( ¤ )__________________( ¤ )_________|                              ||                            ||");
            Console.WriteLine("..............'''....................'''.........................................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                   _____________________                                         ||     |   |       |   |      ||");
            Console.WriteLine("            _    /|         |           \\                                        ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome  _|\\__/ |........ |............\\__________                             ||      ___         ___       ||");
            Console.WriteLine("           |                   -*                    \\                           ||     |   |       |   |      ||");
            Console.WriteLine("           |      ...                    ...          \\<<                        ||     |___|       |___|      ||");
            Console.WriteLine("           |_____( ¤ )__________________( ¤ )_________|                          ||                            ||");
            Console.WriteLine("..................'''....................'''.....................................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                      _____________________                                      ||     |   |       |   |      ||");
            Console.WriteLine("               _    /|         |           \\                                     ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome to  _|\\__/ |........ |............\\__________                          ||      ___         ___       ||");
            Console.WriteLine("              |                   -*                    \\                        ||     |   |       |   |      ||");
            Console.WriteLine("              |      ...                    ...          \\<<                     ||     |___|       |___|      ||");
            Console.WriteLine("              |_____( ¤ )__________________( ¤ )_________|                       ||                            ||");
            Console.WriteLine(".....................'''....................'''..................................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                         _____________________                                   ||     |   |       |   |      ||");
            Console.WriteLine("                  _    /|         |           \\                                  ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome to gr  _|\\__/ |........ |............\\__________                       ||      ___         ___       ||");
            Console.WriteLine("                 |                   -*                    \\                     ||     |   |       |   |      ||");
            Console.WriteLine("                 |      ...                    ...          \\<<                  ||     |___|       |___|      ||");
            Console.WriteLine("                 |_____( ¤ )__________________( ¤ )_________|                    ||                            ||");
            Console.WriteLine("........................'''....................'''...............................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                            _____________________                                ||     |   |       |   |      ||");
            Console.WriteLine("                     _    /|         |           \\                               ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome to group  _|\\__/ |........ |............\\__________                    ||      ___         ___       ||");
            Console.WriteLine("                    |                   -*                    \\                  ||     |   |       |   |      ||");
            Console.WriteLine("                    |      ...                    ...          \\<<               ||     |___|       |___|      ||");
            Console.WriteLine("                    |_____( ¤ )__________________( ¤ )_________|                 ||                            ||");
            Console.WriteLine("...........................'''....................'''............................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                               _____________________                             ||     |   |       |   |      ||");
            Console.WriteLine("                        _    /|         |           \\                            ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome to group 4s  _|\\__/ |........ |............\\__________                 ||      ___         ___       ||");
            Console.WriteLine("                       |                   -*                    \\               ||     |   |       |   |      ||");
            Console.WriteLine("                       |      ...                    ...          \\<<            ||     |___|       |___|      ||");
            Console.WriteLine("                       |_____( ¤ )__________________( ¤ )_________|              ||                            ||");
            Console.WriteLine("..............................'''....................'''.........................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                                   _____________________                         ||     |   |       |   |      ||");
            Console.WriteLine("                            _    /|         |           \\                        ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome to group 4s gar  _|\\__/ |........ |............\\__________             ||      ___         ___       ||");
            Console.WriteLine("                           |                   -*                    \\           ||     |   |       |   |      ||");
            Console.WriteLine("                           |      ...                    ...          \\<<        ||     |___|       |___|      ||");
            Console.WriteLine("                           |_____( ¤ )__________________( ¤ )_________|          ||                            ||");
            Console.WriteLine("..................................'''....................'''.....................||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________"); 
            Console.WriteLine("                                                                                 | Parked vehicles: "+pN+"           | "); 
            Console.WriteLine("                                                                                 | Free spots: "+fS+"                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: "+mN+"     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                                         _____________________                   ||     |   |       |   |      ||");
            Console.WriteLine("                                  _    /|         |           \\                  ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome to group 4s garage!    _|\\__/ |........ |............\\__________       ||      ___         ___       ||");
            Console.WriteLine("                                 |                   -*                    \\     ||     |   |       |   |      ||");
            Console.WriteLine("                                 |      ...                    ...          \\<<  ||     |___|       |___|      ||");
            Console.WriteLine("                                 |_____( ¤ )__________________( ¤ )_________|    ||                            ||");
            Console.WriteLine("........................................'''....................'''...............||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("");
            Thread.Sleep(400);
            Console.Clear();

            Console.WriteLine("");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine(@"                                                                                        //    ======    \\  ");
            Console.WriteLine(@"                                                                                        ||   ||    \\   ||  ");
            Console.WriteLine("                                                                                        ||   ||     ||  ||   ");
            Console.WriteLine("                                                                                        ||   ||    //   ||   ");
            Console.WriteLine("                                                                                        ||   ||====     ||   ");
            Console.WriteLine("                                                                                        ||   ||         ||   ");
            Console.WriteLine(@"                                                                                        \\   ||         //  ");
            Console.WriteLine("                                                                                          ==============     ");
            Console.WriteLine("                                                                                                 |           ");
            Console.WriteLine("                                                                                 ________________________________");
            Console.WriteLine("                                                                                 | Parked vehicles: " + pN + "           | ");
            Console.WriteLine("                                                                                 | Free spots: " + fS + "                | ");
            Console.WriteLine("                                                                                 | Max allowed vehicles: " + mN + "     | ");
            Console.WriteLine("                                                                                 |------------------------------|");
            Console.WriteLine("                                                                                 ||      ___         ___       ||");
            Console.WriteLine("                                         _____________________                   ||     |   |       |   |      ||");
            Console.WriteLine("                                  _    /|         |           \\                  ||     |___|       |___|      ||");
            Console.WriteLine("  Welcome to group 4s garage!    _|\\__/ |........ |............\\__________       ||      ___         ___       ||");
            Console.WriteLine("                                 |                   -*                    \\     ||     |   |       |   |      ||");
            Console.WriteLine("                                 |      ...                    ...          \\<<  ||     |___|       |___|      ||");
            Console.WriteLine("                                 |_____( ¤ )__________________( ¤ )_________|    ||                            ||");
            Console.WriteLine("........................................'''....................'''...............||............................||.....");
            Console.WriteLine("");
            Console.WriteLine("                                                PRESS ANY KEY TO ENTER MENU           ");
            Console.ReadKey();
            Console.Clear();


        }
    }
}
